# public keys
keys:
  - users:
      - &marius_blackbird age1zxj8yvrqvj54ma3cj57v5cl607fppkaerwnqv3trpj9pfqrj8fks3gt5dq
      - &marius_claymore age1gqhr7ath3efqztq3w3rp683k8twa3r69qjh8gsn2azwtts95sddqur36g0
      - &marius_maverick age1lvc9dvv0culkarg6nr6792red90y6lql3ck2fyl724uzz6hjsceq4gq8g9
      - &marius_wingman age13efdjve6ytfr9vzr6kl6awwg2tn50jcjwfltwvk7088lqlykfvvqkhlfp9
      - &marius_oldfart age1fwparx8hy5dtg6y88s08ru4ssadwpw7wt5f9ma9qzuhn6ql9yszqrs9v3a
      - &marius_ironfist age1fmrna6xstwwj502hlt3getv2za0ztclc5tqr38djegc8edmezapqplycx2
  - hosts:
      - &claymore age10lkp093hx5p3q8u3ese80wfd97kkwv3trr3jq5ssh8j8ydnlep4skhh2kf
      - &wingman age18z7saq4mwa06r7r6jch65n65dksvq8rv7w0rdw0fulfu9pdz5qcsr55qz8
      - &maverick age1aef4krvu7nq7ey7et8qzp8ht92gnz58a8dyu3zkzdsdc32a0vcnqth96vt
      - &ironfist age1vfvxxtzhacqhkkn53nzhpx04wqzw5mh9qc8aj5r4hk8jcu7nnp7q60h559
      - &oldfart age1442f9vywmjcenkl4n5rzwg706d4ga4pet0q38dvpzaextk5nnsfszcqdgv
      - &blackbird age1uguluu2x047lsmfsz7ghn6lt7s97nrdvgppxe80pj9fr4ffdna2s2c6fds
creation_rules:
  - path_regex: sops/shared\.yaml$
    key_groups:
      - age:
          - *marius_blackbird
          - *blackbird
          - *marius_claymore
          - *claymore
          - *marius_maverick
          - *maverick
          - *marius_wingman
          - *wingman
          - *marius_oldfart
          - *oldfart
          - *marius_ironfist
          - *ironfist
  - path_regex: sops/blackbird\.yaml$
    key_groups:
      - age:
          - *marius_blackbird
          - *blackbird
  - path_regex: sops/claymore\.yaml$
    key_groups:
      - age:
          - *marius_blackbird
          - *blackbird
          - *marius_claymore
          - *claymore
  - path_regex: sops/maverick\.yaml$
    key_groups:
      - age:
          - *marius_blackbird
          - *blackbird
          - *maverick
          - *marius_maverick
  - path_regex: sops/wingman\.yaml$
    key_groups:
      - age:
          - *marius_blackbird
          - *blackbird
          - *marius_wingman
          - *wingman
  - path_regex: sops/oldfart\.yaml$
    key_groups:
      - age:
          - *marius_blackbird
          - *blackbird
          - *marius_oldfart
          - *oldfart
  - path_regex: sops/ironfist\.yaml$
    key_groups:
      - age:
          - *marius_blackbird
          - *blackbird
          - *marius_ironfist
          - *ironfist
